language: python
python:
  # will support py3 on packaging
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements/test.txt
  - pip install coveralls
  - pip freeze

# command to run tests
script:
  make check

after_success:
  coveralls
